sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t naren9990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naren9990/docker-react npm run test
